# Generated by Django 5.2.15 on 2026-06-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawsource',
            name='text_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
