# Generated by Django 5.2.15 on 2026-06-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('code', 'Кодекс'), ('federal_law', 'Федеральный закон'), ('decree', 'Постановление'), ('order', 'Приказ'), ('other', 'Иное')], max_length=20)),
                ('title', models.TextField()),
                ('official_number', models.CharField(blank=True, max_length=100)),
                ('sign_date', models.DateField(blank=True, null=True)),
                ('issuing_body', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('in_force', 'Действует'), ('repealed', 'Утратил силу'), ('not_in_force', 'Не вступил в силу')], default='in_force', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('official_pub_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
