# Generated by Django 5.2.15 on 2026-06-06 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("redaction_date", models.DateField(help_text="Действует с")),
                ("full_text", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("ingested_at", models.DateTimeField(blank=True, null=True)),
                ("parser_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redactions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-redaction_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "redaction_date"), name="uniq_document_redaction_date"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("document",),
                        name="uniq_current_redaction_per_document",
                    ),
                ],
            },
        ),
    ]
