# Generated by Django 5.2.15 on 2026-06-06 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("raw_citation", models.TextField(blank=True)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("references", "Ссылается на"),
                            ("amends", "Изменяет"),
                            ("amended_by", "Изменён"),
                        ],
                        default="references",
                        max_length=20,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("auto", "Парсер"), ("curator", "Куратор")],
                        default="curator",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("suggested", "Предложена"), ("confirmed", "Подтверждена")],
                        default="suggested",
                        max_length=20,
                    ),
                ),
                ("context", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_links",
                        to="documents.article",
                    ),
                ),
                (
                    "from_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="documents.document",
                    ),
                ),
                (
                    "to_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_links",
                        to="documents.article",
                    ),
                ),
                (
                    "to_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="documents.document",
                    ),
                ),
            ],
        ),
    ]
