# Generated by Django 5.2.15 on 2026-06-06 05:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="redaction",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="article_search_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="redaction",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="redaction_search_gin"
            ),
        ),
    ]
