# Generated by Django 5.2.15 on 2026-06-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_article_article_not_self_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="redaction",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда редакция опубликована в системе (ставится publish()).",
                null=True,
            ),
        ),
    ]
