# Generated by Django 5.2.15 on 2026-06-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_backfill_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='auto_publish',
            field=models.BooleanField(default=False, help_text='Авто-публиковать свежую редакцию из source_url как текущую, без куратора.'),
        ),
    ]
