# Generated by Django 5.2.15 on 2026-06-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_auto_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.TextField()),
                ('official_number', models.CharField(blank=True, max_length=100)),
                ('doc_type', models.CharField(choices=[('code', 'Кодекс'), ('federal_law', 'Федеральный закон'), ('decree', 'Постановление'), ('order', 'Приказ'), ('other', 'Иное')], max_length=20)),
                ('note', models.TextField(blank=True, help_text='Почему ждём / где искать.')),
                ('ips_search_url', models.URLField(blank=True, help_text='Ссылка на поиск ИПС (браузер).')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ожидаемый акт',
                'verbose_name_plural': 'ожидаемые акты',
                'ordering': ['added_at'],
            },
        ),
    ]
