# Generated by Django 5.2.15 on 2026-06-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_pendingact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='kind',
            field=models.CharField(choices=[('section', 'Раздел'), ('chapter', 'Глава'), ('article', 'Статья'), ('point', 'Пункт'), ('appendix', 'Приложение')], default='article', max_length=20),
        ),
    ]
