# Generated by Django 5.2.15 on 2026-06-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_pendingact'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingact',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingact',
            name='eo_number',
            field=models.CharField(blank=True, help_text='Номер ЭО портала опубликования (пусто у ручных).', max_length=40),
        ),
        migrations.AddField(
            model_name='pendingact',
            name='ips_nd',
            field=models.CharField(blank=True, help_text='Привязанный nd ИПС (резолвер/куратор).', max_length=40),
        ),
        migrations.AddField(
            model_name='pendingact',
            name='issuing_body',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pendingact',
            name='publication_url',
            field=models.URLField(blank=True, help_text='Ссылка на акт/PDF на портале.'),
        ),
        migrations.AddField(
            model_name='pendingact',
            name='resolution_status',
            field=models.CharField(choices=[('new', 'Новый'), ('candidate', 'Есть кандидат'), ('bound', 'Привязан'), ('dismissed', 'Отклонён')], default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='pendingact',
            name='source',
            field=models.CharField(choices=[('auto', 'Авто'), ('manual', 'Вручную')], default='manual', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='pendingact',
            constraint=models.UniqueConstraint(condition=models.Q(('eo_number', ''), _negated=True), fields=('eo_number',), name='uniq_pendingact_eo'),
        ),
    ]
