# Generated by Django 5.2.15 on 2026-06-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_article_kind'),
        ('documents', '0014_pendingact_document_date_pendingact_eo_number_and_more'),
    ]

    operations = [
    ]
