# Generated by Django 5.2.15 on 2026-06-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_merge_20260620_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='level',
            field=models.CharField(choices=[('federal', 'Федеральный'), ('regional', 'Региональный'), ('municipal', 'Муниципальный')], default='federal', help_text='Уровень нормативки (Р2). Региональный/муниципальный — на будущее.', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='region_code',
            field=models.CharField(blank=True, help_text='Код субъекта РФ; пусто на федеральном уровне.', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='source_status',
            field=models.CharField(choices=[('official', 'Официальный источник'), ('unofficial', 'Неофициальный источник')], default='official', max_length=20),
        ),
        migrations.AddField(
            model_name='redaction',
            name='text_status',
            field=models.CharField(choices=[('official', 'Официальная редакция'), ('reconstruction', 'Автоматическая реконструкция')], default='official', help_text='Происхождение текста (Р1): official — из официального сводного раздела ИПС; reconstruction — собрано движком/куратором. Ортогонально review_status.', max_length=20),
        ),
    ]
