# Generated by Django 5.2.15 on 2026-06-24 05:57

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_legal_status_fields'),
    ]

    operations = [
        # CREATE EXTENSION IF NOT EXISTS vector — до поля/индекса.
        VectorExtension(),
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='article_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
