# Generated by Django 5.2.15 on 2026-06-29 05:24

from django.db import migrations, models
from django.db.models import Count


def disambiguate_residual_dups(apps, schema_editor):
    """Само-исцеление перед навешиванием ограничения: если в БД остались
    исторические дубли (redaction, anchor) (засеяна до фикса парсера и без
    запуска осмысленной перенумерации), делаем якоря уникальными, добавляя
    суффикс. Номер/заголовок НЕ трогаем (не выдумываем право) — только
    устраняем коллизию якоря, чтобы UniqueConstraint мог встать. На чистой/
    пустой БД (CI, уже починенный dev) — ноль работы."""
    Article = apps.get_model("documents", "Article")
    dup_groups = (
        Article.objects.exclude(anchor="")
        .values("redaction", "anchor")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    for g in dup_groups:
        rows = list(
            Article.objects.filter(redaction_id=g["redaction"], anchor=g["anchor"]).order_by(
                "order", "id"
            )
        )
        # Первую (каноничную по order) оставляем; остальным — уникальный суффикс.
        for i, row in enumerate(rows[1:], start=2):
            new_anchor = f"{row.anchor}-dup{i}"
            while Article.objects.filter(redaction_id=row.redaction_id, anchor=new_anchor).exists():
                i += 1
                new_anchor = f"{row.anchor}-dup{i}"
            row.anchor = new_anchor
            row.save(update_fields=["anchor"])


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_article_embedding_article_article_embedding_hnsw'),
    ]

    operations = [
        migrations.RunPython(disambiguate_residual_dups, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(condition=models.Q(('anchor', ''), _negated=True), fields=('redaction', 'anchor'), name='uniq_redaction_anchor'),
        ),
    ]
