# Generated by Django 5.2.15 on 2026-06-23 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0015_merge_20260620_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=300, verbose_name='Суд / орган')),
                ('decision_date', models.DateField(verbose_name='Дата')),
                ('case_number', models.CharField(blank=True, max_length=100, verbose_name='Номер дела/постановления')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('summary', models.TextField(blank=True, verbose_name='Суть / правовая позиция')),
                ('source_url', models.URLField(blank=True, verbose_name='Источник')),
                ('article_number', models.CharField(blank=True, max_length=50, verbose_name='Статья акта')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_decisions', to='documents.document', verbose_name='Акт')),
            ],
            options={
                'verbose_name': 'Судебное решение',
                'verbose_name_plural': 'Судебная практика',
                'ordering': ['-decision_date', '-id'],
            },
        ),
    ]
