# Generated by Django 5.2.15 on 2026-06-23 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0015_merge_20260620_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='Термин')),
                ('definition', models.TextField(blank=True, verbose_name='Определение')),
                ('article_number', models.CharField(blank=True, max_length=50, verbose_name='Статья акта')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossary_terms', to='documents.document', verbose_name='Акт-источник')),
            ],
            options={
                'verbose_name': 'Термин',
                'verbose_name_plural': 'Глоссарий',
                'ordering': ['term', 'id'],
            },
        ),
    ]
