import pytest

from documents.models import Document
from documents.tests.factories import make_document


@pytest.mark.django_db
def test_document_str_contains_type_and_number():
    doc = make_document()
    assert "Кодекс" in str(doc)
    assert "197-ФЗ" in str(doc)


@pytest.mark.django_db
def test_document_slug_is_unique():
    make_document(slug="tk-rf")
    with pytest.raises(Exception):
        make_document(slug="tk-rf", official_number="X")


from datetime import date

from django.db import IntegrityError, transaction

from documents.models import Redaction
from documents.tests.factories import make_redaction


@pytest.mark.django_db
def test_publish_sets_current_and_unsets_previous():
    doc = make_document()
    first = make_redaction(doc, redaction_date=date(2023, 1, 1))
    first.publish()
    second = make_redaction(doc, redaction_date=date(2024, 1, 1))
    second.publish()

    first.refresh_from_db()
    second.refresh_from_db()
    assert second.is_current is True
    assert second.review_status == Redaction.ReviewStatus.PUBLISHED
    assert first.is_current is False


@pytest.mark.django_db
def test_unique_document_redaction_date():
    doc = make_document()
    make_redaction(doc, redaction_date=date(2024, 1, 1))
    with pytest.raises(IntegrityError):
        with transaction.atomic():
            make_redaction(doc, redaction_date=date(2024, 1, 1))


@pytest.mark.django_db
def test_only_one_current_redaction_per_document():
    doc = make_document()
    make_redaction(doc, redaction_date=date(2023, 1, 1), is_current=True)
    with pytest.raises(IntegrityError):
        with transaction.atomic():
            make_redaction(doc, redaction_date=date(2024, 1, 1), is_current=True)


from documents.models import Article
from documents.tests.factories import make_article


@pytest.mark.django_db
def test_article_anchor_autogenerated_from_number():
    art = make_article(number="81")
    assert art.anchor == "st-81"


@pytest.mark.django_db
def test_article_hierarchy_parent_children():
    red = make_redaction()
    chapter = make_article(
        red, kind=Article.Kind.CHAPTER, number="13", title="Глава 13", order=1
    )
    article = make_article(red, number="81", parent=chapter, order=2)
    assert article.parent == chapter
    assert list(chapter.children.all()) == [article]
